sudo: false
language: python
matrix:
    include:
        - python: 3.6
          env: TOXENV=flake8
        - python: 3.6
          env: TOXENV=pylint
        - python: 3.6
          env: TOXENV=py36
install:
    - pip install tox
script: tox

